apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: frext

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: frext-job-controller
rules:
- apiGroups: ["", "batch"] # "" 标明 core API 组
  resources: ["pods", "jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: frext-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: frext
  namespace: default
roleRef:
  kind: Role
  name: frext-job-controller
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Service
metadata:
  name: frext-compile-svc
spec:
  type: NodePort
  selector:
    app: frext-compile
  ports:
    - protocol: TCP
      port: 8012
      targetPort: 8012

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frext-compile
  labels:
    app: frext-compile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frext-compile
  template:
    metadata:
      labels:
        app: frext-compile
    spec:
      serviceAccountName:
        frext
      initContainers:
      - name: volume-mount-hack
        image: debian:stable-slim
        command: ["sh", "-c", "chown -R 1001:1001 /nexus"]
        volumeMounts:
        - name: fs
          mountPath: /nexus
      containers:
      - name: frext-compile
        image: wxwd14388/frext-compile:v0.2.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8012
        volumeMounts:
          - name: fs
            mountPath: /data/FrexT
      volumes:
        - name: fs
          hostPath:
            path: /root/FrexT_data/frext-file-system/log_compile
            type: Directory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: frext/role
                operator: In
                values:
                - file-system
