apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-ttl
spec:
  # 参数无效？？？？
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "1"
          limits:
            memory: "256Mi"
            cpu: "1"
      restartPolicy: Never
  backoffLimit: 4