apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: ["", "batch"] # "" 标明 core API 组
  resources: ["pods", "jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]